### ISSUE TITLE
Add GCam

### ISSUE THREAD

**Issue by Saksham-245** [PalladiumOS-Devices/device_xiaomi_phoenix#1]
Just a feature requests
 -Please can you add Gcam in this build or next build and remove the default camera app

The rom is perfect just missing is the default Gcam app.

**Comment by chiru2000** [comment]
> Just a feature requests -Please can you add Gcam in this build or next build and remove the default camera app
> 
> The rom is perfect just missing is the default Gcam app.

https://github.com/PalladiumOS-Devices/device_xiaomi_phoenix/commit/c18ab22da6ffed4d26618682fcf0ddecce841fe0
